# Generated by Django 6.1 on 2026-08-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MISSING_VALUE', 'Missing Value'), ('DUPLICATE', 'Duplicate'), ('ANOMALY', 'Anomaly'), ('INVALID_FORMAT', 'Invalid Format')], max_length=30)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('ai_root_cause', models.TextField(blank=True, null=True)),
                ('ai_recommendation', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('column', models.CharField(blank=True, max_length=255, null=True)),
                ('row', models.PositiveIntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='datasets.dataset')),
            ],
        ),
    ]
